-- CREATING DATABASE
CREATE DATABASE WORLD_POPULATION;
USE WORLD_POPULATION;

DROP TABLE WORLD_POPULATION;

-- CREATING TABLE
CREATE TABLE IF NOT EXISTS WORLD_POPULATION
(
	COUNTRY VARCHAR(50),
	AREA INT,
	BIRTH_RATE DECIMAL(4,2),
	DEATH_RATE DECIMAL(4,2),
	INFANT_MORTALITY_RATE DECIMAL(5,2),
	INTERNET_USERS INT,
	LIFE_EXP_AT_BIRTH DECIMAL(4,2),
	MATER178L_MORTALITY_RATE INT,
	NET_MIGRATION_RATE DECIMAL(6,3),
	POPULATION INT,
	POPULATION_GROWTH_RATE DECIMAL(3,2)
);

-- UPLOADING CSV INTO TABLE
LOAD DATA INFILE
'E:\\Data Analysis\\Assignment\\SQL\\Master_project\\World_population_data.csv'
INTO TABLE WORLD_POPULATION
FIELDS TERMINATED BY ','
ENCLOSED BY '"'
LINES TERMINATED BY '\n'
IGNORE 1 ROWS;

SELECT * FROM WORLD_POPULATION;

-- 1. Which country has the highest population?
-- SOLUTION 1
SELECT COUNTRY, POPULATION FROM WORLD_POPULATION ORDER BY POPULATION DESC LIMIT 1;

-- SOLUSTION 2
SELECT COUNTRY, POPULATION FROM
(SELECT COUNTRY, POPULATION, 
ROW_NUMBER() OVER(ORDER BY POPULATION DESC) AS HIGHEST_POPULATION FROM WORLD_POPULATION) TEMP_TABLE
WHERE HIGHEST_POPULATION = 1;

-- 2. Which country has the least number of people?
-- SOLUTION 1
SELECT COUNTRY, POPULATION FROM WORLD_POPULATION ORDER BY POPULATION LIMIT 1;

-- SOLUSTION 2
SELECT COUNTRY, POPULATION FROM
(SELECT COUNTRY, POPULATION, 
ROW_NUMBER() OVER(ORDER BY POPULATION) AS LOWEST_POPULATION FROM WORLD_POPULATION) TEMP_TABLE
WHERE LOWEST_POPULATION = 1;

-- 3. Which country is witnessing the highest population growth?
SELECT COUNTRY, POPULATION, POPULATION_GROWTH_RATE FROM WORLD_POPULATION ORDER BY POPULATION_GROWTH_RATE DESC LIMIT 1;

-- 4. Which country has an extraordinary number for the population?
SELECT COUNTRY, POPULATION FROM WORLD_POPULATION ORDER BY POPULATION DESC LIMIT 1;


-- 5. Which is the most densely populated country in the world?
SELECT COUNTRY,AREA,POPULATION,(POPULATION/AREA) as POPULATION_DENSITY FROM WORLD_POPULATION
ORDER BY POPULATION_DENSITY desc
LIMIT 1;